name: Gradle CI

on:
  push:
    branches: [ "main", "dev" ]   # main, dev 브랜치 push 시 실행
  pull_request:
    branches: [ "main", "dev" ]   # PR 생성 시 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 캐싱 (빌드 속도 개선)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Run headless-safe tests only
        run: ./gradlew test --exclude-task :app:testGui --no-daemon

      # 5. 빌드 & 테스트
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
